services:
  # MongoDB for User-Service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: userservice
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # MongoDB for Comment-Service
  mongodb-comments:
    image: mongo:latest
    container_name: mongodb-comments
    environment:
      MONGO_INITDB_DATABASE: commentservice
    ports:
      - "27018:27017"
    volumes:
      - mongodb_comments_data:/data/db

  # MySQL  for Recipe-Service
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: recipe_platform_db
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql

  # User Service
  user-service:
    image: user-service:latest
    container_name: user-service
    build:
      context: ./user-service
    depends_on:
      - mongodb
    environment:
      MONGODB_PORT: 27017
      MONGODB_HOST: mongodb
    ports:
      - "8081:8081"


  # Recipe Service
  recipe-service:
    image: recipe-service:latest
    container_name: recipe-service
    build:
      context: ./recipe-service
    depends_on:
      - mysql
      - user-service
    environment:
      USER_SERVICE_BASEURL: http://user-service:8081
      COMMENT_SERVICE_BASEURL: http://comment-service:8083
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123
      MYSQL_DB_HOST: mysql
      MYSQL_DB_PORT: 3306
    ports:
      - "8082:8082"

  # Comment Service
  comment-service:
    image: comment-service:latest
    container_name: comment-service
    build:
      context: ./comment-service
    depends_on:
      - mongodb-comments
    environment:
      MONGODB_PORT: 27017
      MONGODB_HOST: mongodb-comments
      USER_SERVICE_BASEURL: http://user-service:8081
      RECIPE_SERVICE_BASEURL: http://recipe-service:8082
    ports:
      - "8083:8083"

  # Api Gateway
  api-gateway:
    image: api-gateway:latest
    container_name: api-gateway
    build:
      context: ./api-gateway
    depends_on:
      - user-service
      - recipe-service
      - comment-service
    environment:
      USER_SERVICE_BASEURL: user-service:8081
      RECIPE_SERVICE_BASEURL: recipe-service:8082
      COMMENT_SERVICE_BASEURL: comment-service:8083

    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./recipe
      dockerfile: Dockerfile
    ports:
      - "4200:4200"

# Volumes
volumes:
  mongodb_data:
  mongodb_comments_data:
  mysql_data:
