server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: INFO
    org.springframework.security: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        # Route to user-service
        - id: user-service
          uri: http://${USER_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/api/users/**

        # Route to recipe-service
        - id: recipe-service
          uri: http://${RECIPE_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/api/recipes/**

        # Route to comment-service
        - id: comment-service
          uri: http://${COMMENT_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/api/comments/**


